### ISSUE TITLE
Feature: User can create an entry

### ISSUE THREAD

**Issue by NateNobleza** [NateNobleza/runner-up#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- In this feature user should be able to create a new entry
- the entry will track date, time, weather, and distance

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
this application will allow users to create, update, read, and delete items that revolve around their running. This application will track their distance, time, date, and the weather they are running in.

- [ ] Create a button that once it is clicked will populate an entry form
- [x] The entry form should include a time input
- [x] The entry form should include a distance form input
- [x] The entry form should include a date input
- [x] The entry form should include a select input that targets weather(sunny, rainy, gloomy, stormy, windy)
- [x] This entry form should have a submit button that will submit a new entry

## 🖼️ Wireframes

![2AD42D2B-1423-4C46-9614-B91235CE7A38](https://github.com/NateNobleza/runner-up/assets/154506686/46db2df3-4cd0-4e17-9879-5c4d484b90d2)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ...
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
